#!/usr/bin/python
# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
### BEGIN LICENSE
#
# This file is part of bumblebee-ui.
#
# bumblebee-ui is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# bumblebee-ui is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bumblebee-ui. If not, see <http://www.gnu.org/licenses/>.
#
### END LICENSE

# UI MODULE
import pygtk
pygtk.require('2.0')
import gtk
import gobject
import appindicator
import pynotify
import gettext
import xdg.Menu

# SYSTEM MODULE
import os
import subprocess
import sys
import fcntl

# ORIGINAL CLASS
#TODO : Make the links to desktop file editor optional
from app.DesktopFile import GetDesktop
from app.AppSettings import IconSet

#Get configurations from config file
import ConfigParser
uiConfig=ConfigParser.ConfigParser()
uiConfig.read('/etc/bumblebee/bumblebee-indicator.conf')

bumblebeeConfig=ConfigParser.ConfigParser()
bumblebeeConfig.read(uiConfig.get('Common', 'ConfigPath'))

vgl_display=bumblebeeConfig.get('bumblebeed','VirtualDisplay').replace(":","")

icon_file_directory=uiConfig.get('Common','IconFileDirectory')
translations_directory=uiConfig.get('Common','TranslationsDirectory')
menu_file_path=uiConfig.get('Common','MenuFile')

applications_setting_path=uiConfig.get('Indicator','DesktopFileEditorPath')


#Settings that are not parsed from config file for now:
default_preferred_apps =[ ['Glxgears', ['glxgears']] ,
                        ['Glxspheres', ['glxspheres']] ]

# I18N MODULE
gettext.install('bumblebee-ui', translations_directory)

#Notification messages :
#TODO Revert when the possibility to turn off the card is back
attention_label=_(u"Bumblebee : ON")
attention_comment=_(u"Bumblebee is in use")
active_label=_(u"Bumblebee : OFF")
active_comment=_(u"Bumblebee is not used anymore")


class BumblebeeIndicator():
#TODO There must be a better way to get the icon than the URI
#FIXME The notification must be replaced when still visible
    def notify_state(self, title, msg, icon_name):
        self.notification= pynotify.Notification(title, msg, IconSet().get_uri(icon_name,48))
        self.notification.set_urgency(pynotify.URGENCY_CRITICAL)
        #FIXME The notification is to slow and this doesn't work
        #self.notification.set_timeout(1000)
        self.notification.show()

# INITIALIZATION OF INDICATOR AND MENU
    def __init__(self):
        self.ind = appindicator.Indicator ("bumblebee-indicator", "bumblebee-indicator", appindicator.CATEGORY_HARDWARE)
        self.ind.set_status (appindicator.STATUS_ACTIVE)
        self.ind.set_icon_theme_path(icon_file_directory)
#TODO The icons style and accesibility must be enhanced : see icons/test directory
        self.ind.set_icon(icon_file_directory + "bumblebee-indicator.svg",_(u'Bumblebee is unactive'))
        self.ind.set_attention_icon (icon_file_directory + "bumblebee-indicator-active.svg",_(u'Bumblebee is active'))

        self.card_state=False
        self.lock_file = "/tmp/.X%s-lock" % vgl_display

        self.build_menu()

        self.menu.show()
        self.ind.set_menu(self.menu)

    def quit(self, widget, data=None):
        gtk.main_quit()

    def build_menu(self):
        self.menu = gtk.Menu()
        self.switch = gtk.CheckMenuItem()
        self.initial_state_checker()
        self.switch.set_sensitive(False)
        self.menu.append(self.switch)

        self.build_menu_separator(self.menu)

        self.prefered_app_submenu = gtk.MenuItem(_(u"Preferred Apps"))
        self.update_menu()
        self.prefered_app_submenu.connect('activate', self.update_menu)
        self.menu.append(self.prefered_app_submenu)

        if applications_setting_path :
            app_settings = gtk.MenuItem(_(u"Configure Apps"))
            app_settings.connect("activate", self.app_configure)
            self.menu.append(app_settings)

#TODO An UI to configure Bumblebee would be nice

        self.build_menu_separator(self.menu)

        quit = gtk.ImageMenuItem(gtk.STOCK_QUIT)
        quit.connect("activate", self.quit)
        self.menu.append(quit)

        self.menu.show_all()

    def build_menu_separator(self, menu):
        separator = gtk.SeparatorMenuItem()
        separator.show()
        menu.append(separator)

# FUNCTIONS TO BUILD THE "PREFERRED APP" MENU FROM THE LOCAL DESKTOP FILES
    def update_menu(self, widget=None):
        pref_menu=gtk.Menu()
        for item_info in default_preferred_apps:
            self.add_submenu_item( pref_menu, item_info)
        if applications_setting_path:
            self.build_menu_separator( pref_menu )
            self.get_configured_entries( pref_menu , xdg.Menu.parse(menu_file_path))
        pref_menu.show()
        self.prefered_app_submenu.set_submenu( pref_menu )

    def add_submenu_item(self, submenu, item_info):
        [Name, Exec] = item_info
        subitem = gtk.MenuItem(label=Name)
        subitem.connect("activate", self.call_app, ['optirun','-f'] + Exec)
        subitem.show()
        submenu.append( subitem )

# FUNCTIONS TO BUILD THE "PREFERRED APP" MENU FROM THE MENU FILE
    def get_configured_entries(self, submenu, menu):
        for entry in menu.getEntries():
            if isinstance(entry, xdg.Menu.Menu):
                self.get_configured_entries(submenu, entry)
            elif isinstance(entry, xdg.Menu.MenuEntry):
                desktopEntry=GetDesktop(entry)
                if desktopEntry.isConfigured():
                    self.add_submenu_item(submenu, desktopEntry.getConfiguredEntry())

# FUNCTIONS TO CHECK FOR THE STATE OF THE INDICATOR
    def initial_state_checker(self):
        if self.attention_state_condition(): self.set_attention_state(notify=False)
        else : self.set_active_state(notify=False)

    def state_checker(self):
        if self.attention_state_condition():
            if self.card_state == False : self.set_attention_state()
        elif self.card_state == True: self.set_active_state()
        return True

    def attention_state_condition(self):
        if os.path.exists(self.lock_file): return True
        else: return False

# FUNCTIONS TO SET THE STATE OF THE INDICATOR AND LAUNCH NOTIFICATION
    def set_attention_state(self, notify=True):
        self.set_status(True, appindicator.STATUS_ATTENTION,
                        attention_label,
                        attention_comment,
                        "bumblebee-indicator-active", notify)

    def set_active_state(self, notify=True):
        self.set_status(False, appindicator.STATUS_ACTIVE,
                        active_label,
                        active_comment,
                        "bumblebee-indicator", notify)

    def set_status(self, status, indicator, label, comment, icon, notify):
        self.ind.set_status(indicator)
        self.card_state = status
        if notify == True: self.notify_state(label, comment, icon)
        self.switch.set_label(label)
        self.switch.set_active(status)

# FUNCTION TO DEFINE THE APPLICATIONS SETTING LINK IN THE INDICATOR

    def app_configure(self,widget):
        self.call_app(widget, [ applications_setting_path ])
        #Applications_settings()

# FUNCTION TO LAUNCH THE APPS WITHIN THE INDICATOR
    def call_app(self, widget, app_exec):
        print app_exec
        print "Command launched through the bumblebee-ui : " + ' '.join(app_exec)
#FIXME There is a problem when closing the launched app and when the indicator has been closed: the indicator is still running : What a daemon!!
        subprocess.Popen(app_exec,shell=False)

# MAIN LOOP LAUNCHING A STATE CHECK EVERY TWO SECONDS
#FIXME This check every two second could be avoid if bumblebee send this signal through dbus with this shell commands,
#The indicator will then know in real time the state of bumblebee and later of the card with an other signal : bumblebee : the code is already there to receive this signal : think to add this two lines at the good place in the ubuntu devel release
#dbus-send --session --dest=org.bumblebee.indicator /org/bumblebee/indicator org.bumblebee.indicator.BumblebeeStarted
#dbus-send --session --dest=org.bumblebee.indicator /org/bumblebee/indicator org.bumblebee.indicator.BumblebeeStopped
    def main(self):
        self.state_checker()
        gobject.timeout_add_seconds(2, self.state_checker)
        gtk.main()

if __name__ == "__main__":
    pid_file = 'bumblebee-indicator.pid'
    fp = open(pid_file, 'w')
    try:
        fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
        indicator = BumblebeeIndicator()
        indicator.main()
    except IOError:
        print "Another instance of bumblebee-indicator is running : Quit"
        quit()

